[package]
name = "hexland"
version = "0.1.0"
authors = ["Alex Holloway <alex.holloway.ctx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
num = "0.3.0"
