#!/bin/bash

echo ""
echo "🔄 Wall & Shadow dev container started!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Service Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  React Dev Server:        http://localhost:5000"
echo "  Firebase Emulator UI:    http://localhost:4000"
echo "  Firebase Hosting:        http://localhost:3400"
echo "  Firebase Functions:      http://localhost:5001"
echo "  Firebase Storage:        localhost:9199"
echo "  Firestore Emulator:      localhost:8080"
echo "  Firebase Auth:           localhost:9099"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tip: Run 'cd was-web && yarn start' to begin"
echo ""
